# Generated by Django 3.0.7 on 2020-08-09 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='в рублях', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ProductType', verbose_name='Тип продукта'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='url',
            field=models.SlugField(max_length=160, unique=True),
        ),
    ]
