# Generated by Django 3.0.7 on 2020-08-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200809_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Обложка'),
        ),
    ]
