# Generated by Django 3.0.7 on 2020-08-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200809_0849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='producttypes',
        ),
    ]
