# Generated by Django 3.0.7 on 2020-08-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200809_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tagline',
        ),
    ]
